/*global _, window, jQuery, Raphael, feed */

var states = {},
    eventsByName = {},
    stateNames= {},
    
    // States
    START =                 0,

    HOVER_DONOR =           1,
    HOVER_RECIPIENT =       2,
    HOVER_MULTILATERAL =    3,

    SELECT_DONOR =          4,
    SELECT_RECIPIENT =      5,
    SELECT_MULTILATERAL =   6,

    HOVER_RECIPIENT_SELECT_DONOR =          7,
    HOVER_MULTILATERAL_SELECT_DONOR =       8,
    HOVER_DONOR_SELECT_RECIPIENT =          9,
    HOVER_MULTILATERAL_SELECT_RECIPIENT =   10,
    HOVER_RECIPIENT_SELECT_MULTILATERAL =   11,
    HOVER_DONOR_SELECT_MULTILATERAL =       12,

    SELECT_DONOR_SELECT_RECIPIENT =         13,
    SELECT_DONOR_SELECT_MULTILATERAL =      14,
    SELECT_MULTILATERAL_SELECT_RECIPIENT =  15,


    // Events
    RESET =                 0,

    ENTER_DONOR =           1,
    ENTER_RECIPIENT =       2,
    ENTER_MULTILATERAL =    3,

    LEAVE_DONOR =           4,
    LEAVE_RECIPIENT =       5,
    LEAVE_MULTILATERAL =    6,

    CLICK_DONOR =           7,
    CLICK_RECIPIENT =       8,
    CLICK_MULTILATERAL =    9;

// states by name look up object
stateNames[START] = "START";
stateNames[HOVER_DONOR] = "HOVER_DONOR";
stateNames[HOVER_RECIPIENT] = "HOVER_RECIPIENT";
stateNames[HOVER_MULTILATERAL] = "HOVER_MULTILATERAL";
stateNames[SELECT_DONOR] = "SELECT_DONOR";
stateNames[SELECT_RECIPIENT] = "SELECT_RECIPIENT";
stateNames[SELECT_MULTILATERAL] = "SELECT_MULTILATERAL";
stateNames[HOVER_RECIPIENT_SELECT_DONOR] = "HOVER_RECIPIENT_SELECT_DONOR";
stateNames[HOVER_MULTILATERAL_SELECT_DONOR] = "HOVER_MULTILATERAL_SELECT_DONOR";
stateNames[HOVER_DONOR_SELECT_RECIPIENT] = "HOVER_DONOR_SELECT_RECIPIENT";
stateNames[HOVER_MULTILATERAL_SELECT_RECIPIENT] = "HOVER_MULTILATERAL_SELECT_RECIPIENT";
stateNames[HOVER_RECIPIENT_SELECT_MULTILATERAL] = "HOVER_RECIPIENT_SELECT_MULTILATERAL";
stateNames[HOVER_DONOR_SELECT_MULTILATERAL] = "HOVER_DONOR_SELECT_MULTILATERAL";
stateNames[SELECT_DONOR_SELECT_RECIPIENT] = "SELECT_DONOR_SELECT_RECIPIENT";
stateNames[SELECT_DONOR_SELECT_MULTILATERAL] = "SELECT_DONOR_SELECT_MULTILATERAL";
stateNames[SELECT_MULTILATERAL_SELECT_RECIPIENT] = "SELECT_MULTILATERAL_SELECT_RECIPIENT";    
    
// events by name look up object
eventsByName["RESET"] = RESET;
eventsByName["ENTER_DONOR"] = ENTER_DONOR;
eventsByName["ENTER_RECIPIENT"] = ENTER_RECIPIENT;
eventsByName["ENTER_MULTILATERAL"] = ENTER_MULTILATERAL;
eventsByName["LEAVE_DONOR"] = LEAVE_DONOR;
eventsByName["LEAVE_RECIPIENT"] = LEAVE_RECIPIENT;
eventsByName["LEAVE_MULTILATERAL"] = LEAVE_MULTILATERAL;
eventsByName["CLICK_DONOR"] = CLICK_DONOR;
eventsByName["CLICK_RECIPIENT"] = CLICK_RECIPIENT;
eventsByName["CLICK_MULTILATERAL"] = CLICK_MULTILATERAL;

// START = state, ENTER_DONOR = condition, HOVER_DONOR = next state:
states[START] = [
    [ENTER_DONOR, HOVER_DONOR],
    [ENTER_RECIPIENT, HOVER_RECIPIENT],
    [ENTER_MULTILATERAL, HOVER_MULTILATERAL]                
];

states[HOVER_DONOR] = [
    [LEAVE_DONOR, START],
    [CLICK_DONOR, SELECT_DONOR]        
];

states[HOVER_RECIPIENT] = [
    [LEAVE_RECIPIENT, START],
    [CLICK_RECIPIENT, SELECT_RECIPIENT]        
];

states[HOVER_MULTILATERAL] = [
    [LEAVE_MULTILATERAL, START],
    [CLICK_MULTILATERAL, SELECT_MULTILATERAL]                
];

states[SELECT_DONOR] = [
    [CLICK_DONOR, HOVER_DONOR],
    [ENTER_RECIPIENT, HOVER_RECIPIENT_SELECT_DONOR],
    [ENTER_MULTILATERAL, HOVER_MULTILATERAL_SELECT_DONOR]                                    
];
  
states[SELECT_RECIPIENT] = [
    [CLICK_RECIPIENT, HOVER_RECIPIENT],
    [ENTER_DONOR, HOVER_DONOR_SELECT_RECIPIENT],
    [ENTER_MULTILATERAL, HOVER_MULTILATERAL_SELECT_RECIPIENT]                                            
];          

states[SELECT_MULTILATERAL] = [
    [CLICK_MULTILATERAL, HOVER_MULTILATERAL],
    [ENTER_RECIPIENT, HOVER_RECIPIENT_SELECT_MULTILATERAL],
    [ENTER_DONOR, HOVER_DONOR_SELECT_MULTILATERAL]                                            
];                          

states[HOVER_RECIPIENT_SELECT_DONOR] = [
    [LEAVE_RECIPIENT, SELECT_DONOR]
];

states[HOVER_MULTILATERAL_SELECT_DONOR] = [
    [LEAVE_MULTILATERAL, SELECT_DONOR]
];

states[HOVER_DONOR_SELECT_RECIPIENT] = [
    [LEAVE_DONOR, SELECT_RECIPIENT]
];

states[HOVER_MULTILATERAL_SELECT_RECIPIENT] = [
    [LEAVE_MULTILATERAL, SELECT_RECIPIENT]
];

states[HOVER_RECIPIENT_SELECT_MULTILATERAL] = [
    [LEAVE_RECIPIENT, SELECT_MULTILATERAL]
];

states[HOVER_DONOR_SELECT_MULTILATERAL] = [
    [LEAVE_DONOR, SELECT_MULTILATERAL]
];

states[SELECT_DONOR_SELECT_RECIPIENT] = [
    [CLICK_DONOR, HOVER_DONOR_SELECT_RECIPIENT],
    [CLICK_RECIPIENT, HOVER_RECIPIENT_SELECT_DONOR]        
];

states[SELECT_DONOR_SELECT_MULTILATERAL] = [
    [CLICK_DONOR, HOVER_DONOR_SELECT_MULTILATERAL],
    [CLICK_MULTILATERAL, HOVER_MULTILATERAL_SELECT_DONOR]        
];

states[SELECT_MULTILATERAL_SELECT_RECIPIENT] = [
    [CLICK_MULTILATERAL, HOVER_MULTILATERAL_SELECT_RECIPIENT],
    [CLICK_RECIPIENT, HOVER_RECIPIENT_SELECT_MULTILATERAL]        
];


// MINIFIES TO:
// var s={};s[0]=[[1,1],[2,2],[3,3]];s[1]=[[4,0],[7,4]];s[2]=[[5,0],[8,5]];s[3]=[[6,0],[9,6]];s[4]=[[7,1],[2,7],[3,8]];s[5]=[[8,2],[1,9],[3,10]];s[6]=[[9,3],[2,11],[1,12]];s[7]=[[5,4],[8,13]];s[8]=[[6,4],[9,14]];s[9]=[[4,5],[7,13]];s[10]=[[6,5],[9,15]];s[11]=[[5,6],[8,15]];s[12]=[[4,6],[7,14]];s[13]=[[7,9],[8,7]];s[14]=[[7,12],[9,8]];s[15]=[[9,10],[8,11]];
